### ISSUE TITLE
[EngAut] Creation of up-to-date action

### ISSUE THREAD

**Issue by Bullrich** [paritytech/up-to-date-action#1]
Creation of an action that keeps all the Pull Request up to date.

As discussed in paritytech/auto-merge-bot#21

```[tasklist]
### Tasks
- [ ] https://github.com/paritytech/up-to-date-action/issues/2
- [ ] https://github.com/paritytech/up-to-date-action/issues/3
- [ ] https://github.com/paritytech/up-to-date-action/issues/4
```

**Comment by Bullrich** [comment]
Task finished sucessful by merging:
- polkadot-fellows/runtimes#139
- polkadot-fellows/runtimes#141

**Comment by Bullrich** [comment]
Update 14/02/2024.

PR has been merged: https://github.com/polkadot-fellows/runtimes/commit/3a134a5c1f06772e6e8a205c170860795cde29be
